# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anIssue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anissuepage',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='anissuepage',
            name='volume',
        ),
        migrations.AddField(
            model_name='anissuepage',
            name='metadata',
            field=models.URLField(default='http://google.com'),
            preserve_default=False,
        ),
    ]
