# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anIssue', '0003_auto_20170720_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='anissuepage',
            name='identifier',
            field=models.CharField(default='mvol-0001-0003-0000', max_length=50),
            preserve_default=False,
        ),
    ]
